[package]
name = "vox-esp32-core"
version = "0.1.0"
authors = ["Raph <iam@raphaeos.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[lib]
name = "vox_esp32_core"
path = "src/lib.rs"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["esp32s3-rgb-led"]
esp32s3-rgb-led = ["rmt-legacy", "smart-leds", "smart-leds-trait", "ws2812-esp32-rmt-driver"]
rmt-legacy = []
timer-legacy = []
pcnt-legacy = []

[dependencies]
log.workspace = true
anyhow.workspace = true
esp-idf-svc.workspace = true
esp-idf-hal.workspace = true
embassy-time.workspace = true
edge-executor.workspace = true
futures.workspace = true

smart-leds = { workspace = true, optional = true }
smart-leds-trait = { workspace = true, optional = true }
ws2812-esp32-rmt-driver = { workspace = true, optional = true }

[build-dependencies]
embuild.workspace = true