[package]
name = "vox-esp32-core"
version = "0.1.0"
authors = ["Raph <iam@raphaeos.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[lib]
name = "vox_esp32_core"
path = "src/lib.rs"
test = false
bench = false
doctest = false

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug = 2     # prefer slower builds but better debugging experience
lto = 'fat'
opt-level = 's'

[features]
default = []
esp32s3-rgb-led = ["rmt-legacy", "smart-leds", "smart-leds-trait"]
rmt-legacy = []
timer-legacy = []
pcnt-legacy = []

[dependencies]
log.workspace = true
anyhow.workspace = true
thiserror.workspace = true
esp-hal.workspace = true
esp-rtos.workspace = true
esp-bootloader-esp-idf.workspace = true
esp-alloc.workspace = true
embedded-hal.workspace = true
embedded-hal-async.workspace = true

embassy-executor.workspace = true
embassy-time.workspace = true
futures.workspace = true
async-channel.workspace = true

smart-leds = { workspace = true, optional = true }
smart-leds-trait = { workspace = true, optional = true }