import { BaseStyle } from "../common.slint";
import { IconButton } from "./icon_button.slint";

export component BackHeader inherits Rectangle {
    in property <string> title <=> title-text.text;
    in property <string> subtitle <=> subtitle-text.text;

    callback back <=> back-button.clicked;

    height: 102px;
    background: BaseStyle.header-background;

    layout := VerticalLayout {
        height: self.preferred-height;
        HorizontalLayout {
            alignment: start;
            height: self.preferred-height;
            padding-left: BaseStyle.default-margin;
            spacing: 12px;
            back-button := IconButton {
                width: 36px;
                height: 36px;
                icon: @image-url("../assets/icons/svg/angle-small-left.svg");
                icon-size: 5px;
                colorize: BaseStyle.text-primary;
            }

            title-text := Text {
                font-size: 24px;
                font-family: BaseStyle.medium-weight;
                color: BaseStyle.text-primary;
            }
        }

        HorizontalLayout {
            height: self.preferred-height;
            padding-left: BaseStyle.default-margin;
            spacing: 12px;
            Rectangle {
                width: 36px;
            }

            subtitle-text := Text {
                font-size: 16px;
                color: BaseStyle.text-tertiary;
                font-family: BaseStyle.medium-weight;
            }
        }
    }

    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 2px;
        background: BaseStyle.header-separator;
    }
}

export component PlainHeader inherits Rectangle {
    in property <string> title <=> title-text.text;

    height: 86px;
    background: BaseStyle.header-background;

    layout := VerticalLayout {
        height: self.preferred-height;
        HorizontalLayout {
            alignment: start;
            height: self.preferred-height;
            padding-left: BaseStyle.default-margin;
            spacing: 12px;

            title-text := Text {
                font-size: 24px;
                font-family: BaseStyle.medium-weight;
                color: BaseStyle.text-primary;
            }
        }
    }

    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 2px;
        background: BaseStyle.header-separator;
    }
}
