import { Page, State, ComponentTheme, BaseStyle } from "../common.slint";

component SideBarIcon inherits Rectangle {
    in-out property <bool> active;
    in-out property <image> icon <=> i.source;
    in-out property <brush> icon-colorize <=> i.colorize;

    callback activate;
    width: ComponentTheme.side-bar.icon-size;
    height: self.width;
    background: active ? ComponentTheme.side-bar.active-background : ta.has-hover ? ComponentTheme.side-bar.active-background.with-alpha(0.2) : Colors.transparent;
    border-radius: ComponentTheme.side-bar.icon-border-radius;

    i := Image {
        width: ComponentTheme.side-bar.icon-image-size;
        height: ComponentTheme.side-bar.icon-image-size;
        colorize: root.active ? ComponentTheme.side-bar.active-icon-color : ComponentTheme.side-bar.inactive-icon-color;
    }

    ta := TouchArea {
        clicked => {
            root.activate();
        }
    }
}

export component Sidebar inherits Rectangle {
    background: ComponentTheme.side-bar.background;
    x: 0px;
    width: BaseStyle.side-bar-width;

    VerticalLayout {
        width: self.preferred-width;
        padding-top: BaseStyle.default-margin;
        spacing: BaseStyle.default-margin;
        alignment: start;

        for page-data[index] in [
            { icon: @image-url("../assets/icons/svg/home.svg"), page: Page.home },
            { icon: @image-url("../assets/icons/svg/lightbulb-on.svg"), page: Page.lights },
            { icon: @image-url("../assets/icons/svg/plug-circle-bolt.svg"), page: Page.power },
            { icon: @image-url("../assets/icons/svg/shower.svg"), page: Page.hotwater },
            { icon: @image-url("../assets/icons/svg/chart-network.svg"), page: Page.devices },
            { icon: @image-url("../assets/icons/svg/settings.svg"), page: Page.settings },
        ]: SideBarIcon {
            activate => {
                State.active-page = page-data.page;
            }
            icon: page-data.icon;
            active: State.active-page == page-data.page;
        }
    }
}
