[workspace]
members = ["vox-esp32-blank", "vox-esp32-testing"]
resolver = "2"

[workspace.dependencies]
log = "0.4"
anyhow = "1.0"

# --- Core ESP32 & Embedded HALs ---
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
esp-idf-hal = "0.46.2"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embassy-time = { version = "0.5", features = ["generic-queue-8"] }

# --- Math & Data Parsing (No Standard Library) ---
num-traits = { version = "0.2.19", default-features = false }
heapless = "0.9.3"         # Fixed-capacity collections (Vec, String, Map) with NO heap allocation
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
postcard = { version = "1.1.3", default-features = false, features = ["alloc", "use-alloc"] }

# --- UI, Displays, & Sensor Interfacing ---
embedded-graphics = "0.8.2" # Standard engine to draw text, shapes, and UIs on screens
mipidsi = "0.10.0"           # Common SPI display driver framework (ST7789, ILI9341 screens)
smart-leds = "0.4.0"
smart-leds-trait = "0.3.2"
ws2812-esp32-rmt-driver = { version = "0.14.0", features = ["smart-leds-trait"] }

# --- Cryptography & Security (Off-Grid Messaging) ---
chacha20poly1305 = { version = "0.11.0", default-features = false, features = ["alloc"] } # Fast authenticated encryption
sha2 = { version = "0.11.0", default-features = false } # Hashing and integrity verification

# --- Build Deps ---
embuild = "0.33"