[package]
name = "vox-esp32-blank"
version = "0.1.0"
authors = ["Raph <iam@raphaeos.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "vox-esp32-blank"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[dependencies]
log.workspace = true
anyhow.workspace = true
esp-idf-svc.workspace = true
esp-idf-hal.workspace = true
embassy-time.workspace = true

vox-esp32-core.workspace = true

[build-dependencies]
embuild.workspace = true