[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]

[build]
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]

[source.panamax]
registry = "http://localhost:8000/git/crates.io-index"

[source.panamax-sparse]
registry = "sparse+http://localhost:8000/index/"

[source.crates-io]
# To use sparse index, change "panamax" to "panamax-sparse".
replace-with = "panamax"